### ISSUE TITLE
There is a problem and I hope to get your help.

### ISSUE THREAD

**Issue by realZhangChi** [cmendible/dotnetcore.samples#4]
In my project, I configured it in Program.cs according to your code, but there was an exception while running. This is the exception details:
Interop.Crypto.OpenSslCryptographicException
  HResult=0x2006D080
  Message=error:2006D080:BIO routines:BIO_new_file:no such file
  Source=System.Security.Cryptography.X509Certificates
  StackTrace:
   at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, String fileName, String password)
   at FreshShop.Identity.Program.<>c__DisplayClass1_0.<CreateWebHostBuilder>b__1(ListenOptions listenOptions) in D:\Users\Chi\source\repos\FreshShop\FreshShop.Identity\Program.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPEndPoint endPoint, Action`1 configure)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPAddress address, Int32 port, Action`1 configure)
   at FreshShop.Identity.Program.<>c.<CreateWebHostBuilder>b__1_0(KestrelServerOptions options) in D:\Users\Chi\source\repos\FreshShop\FreshShop.Identity\Program.cs:line 27
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
![image](https://user-images.githubusercontent.com/13272730/51463856-479d2f80-1d9f-11e9-9c84-14ee1eea4baf.png)
I don't understand where the cert.ptx file is.
I don't know where the error occurred and I hope to get your help. Thank you

**Comment by cmendible** [comment]
Hi the pfx file should be in the same folder as your binaries. Check the dockerfile nd let me know.
